cppit/jucipp

juci/config.cc
juci/config.json
juci/juci.cc
juci/notebook.cc
juci/notebook.h
juci/source.cc
juci/source.h
juci/terminal.cc

There are alot of really simple getters and setters, these should be removed at some point. Direct access to class members should be allowed, and this will result in smaller and simpler code. Bjarne Stroustrup agrees with this btw:)
Some cleanup should also be done with respect to model, view, controller as well. Not entirely sure how best to do this yet however. I could try to clean up source.h and source.cc maybe, and we could use this as a base for the rest of the classes. This would include getting rid of the simple getter and setter methods in these classes (source.h). 
I will also try to find the reason behind the segmentation fault when you open/close tabs several times.

Improved indentention and some fixes

---

juci/CMakeLists.txt
juci/config.cc
juci/config.h
juci/config.json
juci/notebook.cc
juci/notebook.h
juci/selectiondialog.cc
juci/selectiondialog.h
juci/singletons.cc
juci/singletons.h
juci/source.cc
juci/source.h
juci/tooltips.cc
juci/tooltips.h
juci/window.cc
juci/window.h

Had to create a better tooltip-class, the one from gtk was pretty bad. The warning and error messages are maybe a bit eager (based on mouse and text-cursor), but one can maybe add options for that in the future. 
One could also use the Tooltips class to add tooltips for parameters of class functions after completion.

Diagnostics on the fly

---

src/CMakeLists.txt
src/directories.cc
src/juci.cc
src/logging.h
src/menu.cc
src/notebook.cc
src/notebook.h
src/selectiondialog.cc
src/source.cc
src/source.h
src/sourcefile.cc
src/sourcefile.h
src/terminal.cc
src/tooltips.cc
src/window.cc

Tested on Ubuntu 14, debian stable/testing, OS X and MSYS2. 
The clang indentation should now work flawlessly (hopefully) in every case, even in multi-line expressions. 
Would be nice if we could merge this soon, after you have tested it of course. If there are issues, I will try fix it Today or Tomorrow, but I will not commit more features before it's merged:)

Many bug fixes and improved clang indentation

---

src/CMakeLists.txt
src/dialogs.h
src/dialogs_win.cc

* Introduce boost.locale dependency in Msys, no need to update dependencies since it is automatically installed when installing boost
* Fix crashes due to special characters
* Correct start directory is now selected, slightly different behavior than gtk due to windows conventions
* Default file extension is selected as .cpp 
* Less copies due to move semantics

Dialogs now has equal behaviour

---

docs/install.md

* Add arch install instuctions
* Remove gtkmm3 as dependency (it gets automatically installed by gtksourceviewmm)
Before merge

Adding arch install instructions and removal of gtkmm3 dependencies

---

src/files.h

If this works better for your Arch Linux we can merge this before v1.0.0 release.
Tested on:

Correct next/previous tab keys for Linux

---

CMakeLists.txt

Install location matches http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
Previous process of installation would attempt to create a directory before the install process, preventing usage in something like the Arch User Repository.
This also removes the need to workaround any bugs present with desktop file installation tools.

Install desktop file in a portable, build-dir-independent way

---

src/selectiondialog.cc
src/selectiondialog.h
src/source.cc
src/source_clang.cc

Now indent left after '{', so that you do not need to use shift-tab when writing:
```c++
if(true)
{
//do something
}
```

Better support for Allman bracket style (break before bracket)

---

src/files.h

Keybinding for compile_and_run was defined twice

Removed redundant keybinding

---

docs/install.md
src/CMakeLists.txt
src/cmake.cc
src/config.cc
src/config.h
src/debug.cc
src/debug.h
src/debug_clang.cc
src/debug_clang.h
src/dialogs.cc
src/directories.cc
src/directories.h
src/dispatcher.cc
src/dispatcher.h
src/files.h
src/juci.cc
src/menu.cc
src/menu.h
src/notebook.cc
src/notebook.h
src/project.cc
src/project.h
src/selectiondialog.cc
src/selectiondialog.h
src/source_clang.cc
src/source_clang.h
src/terminal.cc
src/terminal.h
src/window.cc
src/window.h

* Now supports running html, python, js and md files
* Window class now contains less code, moved some code to a new class Project and its subclasses
* ~~A bit of work left, want to move the remaining debug source code from Window to a Project singleton class for instance (not yet decided best way to do this)~~

Project cleanup - easier to support compile/run/debug for other languages

---

src/project.cc
src/selectiondialog.cc
src/selectiondialog.h

@zalox merge this as well to your branch. Made the run path equal to the project path so that new C++ users can read and write files in the project path without adding a relative/absolute path. Also now safely clears the tree store when selection dialogs are hidden.

Minor fixes

---

src/debug_clang.cc
src/directories.cc
src/dispatcher.cc
src/project.cc
src/source_clang.cc
src/terminal.cc

As per [`std::mutex::lock()`](http://en.cppreference.com/w/cpp/thread/mutex/lock) documentation:
> `lock()` is usually not called directly: `std::unique_lock` and `std::lock_guard` are used to manage exclusive locking. 
This is of course due to violated exception safety if any function throws.

replaced direct lock()/unlock() calls to mutex with unique_lock

---

src/window.cc

removing `using namespace std;` and usage of `endl`, replacing it with `\n`
Usage of `using namespace std;` is [questionable](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-in-c-considered-bad-practice) and `std::endl` is a badly designed manipulator - it does a different thing that the name indicates: it outputs a newline *and* flushes the output. I've taken the liberty of removing `return 0;`, although I don't mind it that much.
Why does it matter for the IDE? Even though it's a minor point, the sample created by IDE should be *spotless*, as this is the first thing the Random Joe sees when he creates new project, it influences the first experience with the new IDE, so we don't want to encourage bad style in the samples. Also many other C++ IDEs fail the "Hello …

changed main() created by "New C++ project" option

---

src/python_interpreter.cc

See https://bugs.python.org/issue18395 . Essentially, the function that's used here was internal to Python, but released with a public name only recently in 3.5.

Backported Py_DecodeLocale from 3.5

---

src/project_build.cc

Nuke raw calls to `new` from orbit, any one of them becomes a potential to leak.
I'm seriously considering backporting `make_unique` and replacing all calls to `new` with it.

Fixed minor memory leak

---

README.md
docs/api.md
src/files.h
src/menu.cc
src/source.h
src/source_clang.cc
src/window.cc

Works if implementation file is opened and parsed. Header files are not considered, use Go to Declaration instead then. Still pretty useful.

Added: Go to Implementation

---

src/config.cc
src/config.h
src/files.h
src/source.cc

Determines what kind of whitespaces should be drawn. Use comma-separated
list of: space, tab, newline, nbsp, leading, text, trailing or all.

Add draw_spaces option

---

src/project.cc
src/project.h
src/project_build.cc
src/project_build.h
src/source_clang.cc
src/terminal.cc
src/window.cc

I'm much more happy with the project files now, and its usage is more readable and makes more sense to new contributors I think. 
::create is used in gtkmm for creating new special instances, so I stuck to this pattern. 
@zalox Refactorings such as these are pretty safe, but have tested on most platforms. Merge whenever:)

Refactor: src/project* files

---

CMakeLists.txt
tests/CMakeLists.txt
tests/cmake_test.cc
tests/example_test.cc
tests/stubs/config.cc
tests/stubs/dialogs.cc
tests/stubs/dispatcher.cc
tests/stubs/info.cc
tests/stubs/terminal.cc

To enable testing ~~(only works with g++, clang did not support the needed linking options)~~:
```sh
cmake -DENABLE_TESTING=1 ..
make
make test
```
If you are on a terminal only environment without a display server, like Travis CI:
```sh
broadwayd&
make test
```

Added initial tests

---

cmake_modules/FindLibClang.cmake

I needed to add version 3.8.0 in OS X cause brew installed libclang in /usr/local/Cellar/llvm/3.8.0/lib/libclang.dylib
I did just followed the instruction provided on how to install dependencies in OS X and did not change the directory or version of llvm or where should be installed.

Added LLVM version 3.8.0 installed by brew in OS X

---

src/ctags.cc

A segmentation fault occurs when `Ctags::get_location` gets a large line. 
I don't know whether this is normal behaviour, but when juCi++ fell back to ctags it parsed the `./docs` directory as well. A html file had a line of > 40 000 chars, resulting in a failure by the regex library.

Fixes segmentation fault when using ctags on very long lines

---

docs/install.md

gtksourceviewmm3 is now properly part of homebrew and can be installed directly instead of using homebrew/x11/gtksourceviewmm3.

Corrected install instructions for OS X

---

src/menu.cc
src/notebook.cc
src/notebook.h
src/window.cc

Adds a menu option to reload the current file.
Normally when a file is changed from outside of juCi++, it first has to be closed completely and then re-opened in order to work with these changes.
In case of a race while using this PR (a file was changed externally and juCi++ has unsaved changes), upon clicking "Reload File" in the menu, the function will always be executed, but the user is asked if they want to save the current file before it's opened. There's no merging and no backups, either the file on the drive is overwritten or the changes within the editor are overwritten.
To fix this, it would make sense to add an extra warning beforehand, or, instead of an overwriting save, open the "Save File As" prompt, to give the user the option to save his current changes to a separate file …

Reload file

---

src/source.cc

Use  'Ctrl - Right Click' to go to implementation is a very handy feature offered by other IDEs, Jucipp should have it also. :)

Add handy shortcut: use 'Ctrl - Right Click' to go to implementation directly.

---

CMakeLists.txt
docs/install.md

Fix 1: Fixed typo in the install instructions.
Fix 2: Set -mwindows flag as default on Windows. At the moment opening the application spawns a terminal in the background.  [-mwindows](https://gcc.gnu.org/onlinedocs/gcc/x86-Windows-Options.html)

typo and mwindows flag

---

docs/install.md

You will notice that in the `cmake` step, I added the option `-DCMAKE_INSTALL_PREFIX=/usr` since, 99% of the time, that's the path you want to use. Unless that's already the default and I haven't noticed.

Add installation instructions for Opensuse

---

CMakeLists.txt
src/config.cc
src/config.h
src/files.h
src/source.cc

Add right margin line in sourceview. The margin can be activated and configured in the source section of the config file.

Add right margin line in sourceview

---

src/compile_commands.cc
src/source.cc
src/usages_clang.cc

Adds support for OpenCL similar to the support for CUDA added in https://github.com/cppit/jucipp/issues/357.
Support includes:
- auto completion for OpenCL C 2.0 standard-library functions
- documentation tooltips for OpenCL standard-library functions (as long as documented in the [header](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/opencl-c.h))

Adds support for OpenCL source-files

---

src/dispatcher.h
src/menu.h
src/selection_dialog.h
src/tooltips.h

On my system, it was necessary to add these includes in order to compile. Without this, it doesn't recognize `std::function<>`.
My system is ubuntu 16.04, cmake 3.9.0, g++ 5.4.0.

add includes necessary to compile
