- juci/notebook.cc
- juci/notebook.h
- juci/source.cc
- juci/source.h
First step in making the code cleaner and more C++ friendly. Hopefully I did not break anything!
See especially the comment on Source::Controller::is_saved and Source::Controller::is_changed.
> Code cleanup of Source::Controller and Source::Model (renamed Source::Parser)

- juci/selectiondialog.cc
- juci/source.cc
- juci/source.h
Managed to break the '}' key, but it works now. Also the autocompletion is more optimised, should now not experience any delay at all while writing code.
> Smaller fixes

- juci/source.cc
I forgot to push this commit. The messages in console should be gone now.
> Removed temporary testing output.

- juci/source.cc
- juci/source.h
Trying not to create TOO many pull requests, but this one is fixing an annoying issue while writing code. 
Btw, would you mind me setting dark theme on (https://developer.gnome.org/gtkmm/stable/classGtk_1_1Settings.html#a40ac901fea4b95dedf972ed5aa971c51) as default with appropriate colours (configurable in the json-file)? I'm not used to coding with white background:) Or do you prefer having a light theme as default?
> Autocomplete and reparse working together

- README.md
- docs/install.md
minor issue: readme file "## Dependencies ##
Please install these dependencies on your system." did not include boost, gtkmm and gtksourceview which is all needed to run cmake .
> CHANGE: updated  readme file to include libraries needed to run cmake .

- juci/api.cc
- juci/config.cc
- juci/config.json
- juci/directories.cc
- juci/directories.h
- juci/juci.cc
- juci/juci.h
- juci/menu.cc
- juci/menu.h
- juci/notebook.cc
- juci/notebook.h
- juci/source.cc
- juci/source.h
- juci/window.cc
- juci/window.h
This has been long overdue, although I might have broken something. Making pull request now, however, since it affects so many parts of Juci++.
> Cleanup of notebook.* and window.*

- src/entrybox.cc
- src/entrybox.h
- src/files.h
- src/notebook.cc
- src/selectiondialog.cc
- src/selectiondialog.h
- src/source.cc
- src/source.h
- src/window.cc
If ok, could we merge these two commits before Monday morning?
> A quick pull request of two neat commits till Monday

- src/source.cc
- src/window.cc
Merging this right away, since it's a big issue with Ubuntu users.
> Quick fix to weird Ubuntu and possibly other platform key-state. 

- src/source.cc
Quick pull request to fix a crash
> Workaround to iter_forward_to_context_class_toggle bug.

- src/source.cc
- src/source.h
Also a speed up when using source map with huge source files.
> Quick pull request to fix Ubuntu 14 compilation

- src/source.cc
Merging this minor commit as well, since it is related to last merge.
> Minor fix to similar_tokens_tag at buffer change.

- src/notebook.cc
- src/source.cc
- src/source.h
Hopefully we can merge this before I start working on more features on Monday.
> Minor bug fixes

- src/config.cc
- src/files.h
- src/source_clang.cc
- src/terminal.h
- src/window.cc
* clang-format can now be edited in config.json 
* directories automatically update when editing filters
Please review and merge
> More configuration

- CMakeLists.txt
- share/juci.desktop
Merging right away since it fixes mostly the Ubuntu menu bug. Also one can now open files through a file manager using juCi++.
> Desktop file for Linux

- CMakeLists.txt
- docs/install.md
- share/juci.desktop
- src/CMakeLists.txt
- src/cmake.cc
- src/config.cc
- src/config.h
- src/directories.cc
- src/directories.h
- src/files.h
- src/menu.cc
- src/source.h
- src/source_clang.cc
- src/source_clang.h
- src/window.cc
Note that like rename refactor, Go to Usage only considers open and parsed buffers.
> Go to Usage implementation

- .gitmodules
- README.md
- src/directories.cc
- src/directories.h
- src/notebook.cc
- src/notebook.h
- src/source.cc
- src/source.h
- src/source_clang.cc
- src/source_clang.h
- src/window.cc
- src/window.h
We should wait a few days before merging the latest commit (https://github.com/eidheim/jucipp/commit/7b78a6aea9ee5a8ecbf2935b397be50bcae34737) as it needs more testing. 
Same goes for this commit: https://github.com/eidheim/jucipp/commit/fd4668bfe4f313aeee46cc593daaf1d823a76c67
> Major cleanup of clang parsing and autocomplete

- .gitmodules
- src/config.cc
- src/directories.cc
- src/directories.h
- src/files.h
- src/juci.cc
- src/source.cc
- src/source_clang.cc
- src/window.cc
Tested on OS X, MSYS2, Debian stable/testing and Ubuntu 14. Ready for merge.
> Better auto indent tab char and size setting and link to improved tiny-process-library

- docs/install.md
I misunderstood, #116 was from master into this branch, not the other way which I thought first. Merging the minor install doc into master as well then.
> Minor update to install docs

- src/cmake.cc
- src/config.cc
- src/juci.cc
- src/menu.cc
- src/notebook.cc
- src/source_clang.cc
- src/terminal.cc
- src/window.cc
some files has `#include <iostream>` and `using namespace std;` which were marked to be removed, this branch does the same.
> Removed  and  as per the TODO's

- docs/install.md
- src/cmake.cc
- src/cmake.h
- src/config.cc
- src/config.h
- src/files.h
- src/notebook.cc
- src/source_clang.cc
- src/terminal.cc
- src/window.cc
Lets wait a day or two till we have gotten some feedback (positive or otherwise) on this solution
> Build dir fixed

- docs/install.md
- src/directories.cc
- src/source.cc
- src/source_clang.cc
Merging this now as the commits contain no dangerous changes, and also fixes a crash (although most likely noone but me has experienced it).
> Most notably fixes a crash that might happen if contents of subdirectories changed

- docs/install.md
> Installation instructions for Fedora 23

- src/window.cc
using [↑][⇄][↓] for "Find Previous", "Replace current", "Find Next"
see issue #170
> added gui buttons for finding/replacing

- src/config.cc
- src/config.h
- src/files.h
- src/project.cc
- src/source.cc
- src/terminal.cc
- src/terminal.h
- src/window.cc
Fixes #179. Ready for merge after being tested on the various platforms. Consider this v1.1.2 release candidate.
> Terminal and fonts

- CMakeLists.txt
- src/CMakeLists.txt
@eidheim Please review and merge if ok!
> Cleanup of CMakeLists.txt

- src/directories.cc
- src/directories.h
This pull request adds a new feature to the directory tree: ability to create new files with the option in the context menu.
> added new directory tree feature: create new file here

- src/debug_clang.cc
> fixed issue with removing breakpoints

- src/CMakeLists.txt
- src/debug_clang.cc
- src/directories.cc
- src/info.cc
- src/info.h
- src/notebook.cc
- src/project_build.cc
- src/selectiondialog.cc
- src/source.cc
- src/source_clang.cc
- src/terminal.cc
- src/window.cc
- src/window.h
@zalox Feel free to merge if you are happy with it
* Animations (scroll down/up) will be added once https://bugzilla.gnome.org/show_bug.cgi?id=710888 is resolved. 
* Never mind the enormous diff in `src/source_clang.cc`, it's just that diff fails to handle indentation changes in a readable manner.
> Added brief info messages to top right corner

- src/terminal.cc
- src/terminal.h
navigates to the file with error
> Clicking on compiler error in terminal

- src/notebook.cc
- src/source.cc
- src/source.h
Shows info message when a file has changed on disk.
> feature: show warning when files have changed on disk outside of juCi++

- src/config.cc
- src/config.h
- src/dialogs.cc
- src/dialogs.h
- src/info.cc
- src/info.h
- src/notebook.h
- src/source.cc
- src/source.h
- src/source_clang.cc
- src/source_clang.h
- src/window.cc
@zalox you should probably test this a bit too. I think it's 100% and have tested on most platforms.
> Cleanup of refactoring methods

- cmake_modules/FindLibClang.cmake
- src/CMakeLists.txt
- src/directories.cc
- src/git.cc
A set of changes that makes juCi++ build without trouble on FreeBSD.
> builds on FreeBSD. related to #253

- src/config.cc
- src/debug_lldb.cc
- src/dialogs.cc
- src/git.cc
- src/notebook.cc
- src/project.cc
- src/selectiondialog.cc
- src/source.cc
- src/source_clang.cc
- src/source_spellcheck.cc
- src/terminal.cc
- src/window.cc
I did the dirty work and replaced all occurrences of C-Style `NULL` macro usage in API calls with C++11's `nullptr` as they are guaranteed to be compatible.
> Replaced NULL with nullptr wherever applicable.

- CMakeLists.txt
- src/files.h
- src/menu.cc
- src/window.cc
Enables the user to clear the console manually by selecting Window -> Clear Console ~~or hitting Ctrl+Shift+C (keyboard shortcut pending review)~~ edit: or by setting a new keyboard shortcut
> Added way to clear console manually

- src/selectiondialog.cc
- src/source.cc
- src/source_spellcheck.cc
- src/terminal.cc
- src/window.cc
I hope this is more inline with what was intended :)
> fixed numpad return not applying indents

- src/source.cc
- src/source.h
- src/source_diff.cc
Same as https://github.com/cppit/jucipp/pull/279 but without the detour.
Will still fail the tests for some reason, most likely the Project singleton.
> Added breakpoint on click functionality

- src/config.cc
- src/config.h
- src/debug_lldb.cc
- src/directories.cc
- src/git.cc
- src/git.h
- src/juci.cc
- src/notebook.cc
- src/notebook.h
- src/project.cc
- src/source.cc
- src/source.h
- src/source_clang.cc
- src/source_clang.h
- src/source_diff.cc
- src/source_diff.h
- src/window.cc
- tests/source_clang_test.cc
* Added filename and branch to status bar at bottom
* Added colors to diagnostics; number of warnings, errors and fix-its
* Cleanup of status processing
Need feedback on the changes before merge.
> Status bar

- src/ctags.cc
- src/juci.cc
- src/meson.cc
- src/source_clang.cc
This PR includes support for operators. Should be 100%, but should be tested a few days before merge.
> Improved libclang tooltips and navigation

- src/CMakeLists.txt
- src/menu.cc
- src/menu.h
- src/source.cc
- src/window.cc
* Right clicking in source buffer now displays the edit buffer
* Right click selects the hovering line
* Able to toggle comments easy
* Rename rename to refactor rename
> New right click menu

- src/window.cc
Noticed this one was still a question mark.
> Added about dialog logo

- src/files.h
- src/menu.cc
- src/notebook.cc
- src/notebook.h
- src/window.cc
Tested it with Ubuntu 16.04. (Can test it with a Mac if needed)
> Adding a menu item to toggle Tabs visibility
